theme: jekyll-theme-minimal
title: "PwdHash2 - secure site based passwords"
description: "PwdHash2 is a Firefox Add-On and can be used as a PwdHash alternative"
show_downloads: false
logo: /assets/pwdhash-96.png
