theme: jekyll-theme-minimal
title: "PwdHash2 - secure site based passwords"
description: "PwdHash2 is a Firefox Add-On and can be used as an PwdHash alternative"
show_downloads: false
logo: pwdhash-96.png